version: "2"
services:
  mysql:
    image: mysql:5.7
    restart: 'always'
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=financeapp_backend_node
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
  web:
    build: .
    volumes:
      - ./:/src
    ports: ["8080:3000"]
    depends_on:
      - mysql
